#!/usr/bin/python
# -*- coding: UTF-8 -*-

#mythril中可检测漏洞的swc id与swc命名的映射
mythril_dict={"101":"Integer Overflow and Underflow",
              "104":"Unchecked Call Return Value",
              "105":"Unprotected Ether Withdrawal",
              "106":"Unprotected SELFDESTRUCT Instruction",
              "107":"Reentrancy",
              "110":"Assert Violation",
              "111":"Use of Deprecated Solidity Functions",
              "112":"Delegatecall to Untrusted Callee",
              "113":"DoS with Failed Call",
              "114":"Transaction Order Dependence",
              "115":"Authorization through tx.origin",
              "116":"Timestamp Dependence",
              "120":"Weak Sources of Randomness from Chain Attributes",
              "127":"Arbitrary Jump with Function Type Variable",
              "128":"DoS With Block Gas Limit"}

#mythril可检测漏洞的swc参考地址
reference1_dict={"101":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-101",
              "104":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-104",
              "105":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-105",
              "106":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-106",
              "107":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-107",
              "110":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-110",
              "111":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-111",
              "112":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-112",
              "113":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-113",
              "114":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-114",
              "115":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-115",
              "116":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-116",
              "120":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-120",
              "127":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-127",
              "128":"https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-128"}

#oyente中可检测漏洞与swc id的映射
oyente_id={"Integer Overflow and Underflow":"101",
           "Parity Multisig Bug 2":"001",
           "Callstack Depth Attack Vulnerability":"002",
           "Transaction Order Dependence":"114",
           "Timestamp Dependency":"116",
           "Reentrancy":"107"}

#oyente命名与swc统一命名的映射
oyente_dict={"Integer Underflow":"Integer Overflow and Underflow",
             "Integer Overflow":"Integer Overflow and Underflow",
             "Parity Multisig Bug 2":"Parity Multisig Bug 2",
             "Callstack Depth Attack Vulnerability":"Callstack Depth Attack Vulnerability",
             "Transaction-Ordering Dependency":"Transaction Order Dependence",
             "Timestamp Dependency":"Timestamp Dependency",
             "Re-Entrancy Vulnerability":"Reentrancy"}

#slither命名与swc统一命名的映射
slither_dict={"incorrect-versions-of-solidity":"Outdated Compiler Version",
            "old-versions-of-solidity":"Outdated Compiler Version",
            "different-pragma-directives-are-used":"Floating Pragma",
            "unchecked-low-level-calls":"Unchecked Call Return Value",
            "low-level-calls":"Unchecked Call Return Value",
            "functions-that-send-ether-to-arbitrary-destinations":"Unprotected Ether Withdrawal",
            "suicidal":"Unprotected SELFDESTRUCT Instruction",
            "reentrancy-vulnerabilities":"Reentrancy",
            "uninitialized-storage-variables":"Uninitialized Storage Pointer",
            "deprecated-standards":"Use of Deprecated Solidity Functions",
            "controlled-delegatecall":"Delegatecall to Untrusted Callee",
            "dangerous-usage-of-tx.origin":"Authorization through tx.origin",
            "block-timestamp":"Timestamp Dependence",
            "void-constructor":"Incorrect Constructor Name",
            "state-variable-shadowing-from-abstract-contracts":"Shadowing State Variables",
            "local-variable-shadowing":"Shadowing State Variables",
            "state-variable-shadowing":"Shadowing State Variables",
            "right-to-left-override-character":"Right-To-Left-Override control character (U+202E)",
            "unused-state-variables":"Presence of unused variables",
            "dangerous-strict-equalities":"Unexpected Ether balance",
            "uninitialized-state-variables":"Uninitialized State Variables",
            "incorrect-erc20-interface":"Incorrect Erc20 Interface",
            "incorrect-erc721-interface":"Incorrect Erc721 Interface",
            "contracts-that-lock-ether":"Contracts That Lock Ether",
            "constant-functions-using-assembly-code":"Constant Functions Using Assembly Code",
            "constant-functions-changing-the-state":"Constant Functions Changing The State",
            "unchecked-send":"Unchecked Send",
            "uninitialized-local-variables":"Uninitialized Local Variables",
            "unused-return":"Unused Return",
            "builtin-symbol-shadowing":"Builtin Symbol Shadowing",
            "calls-inside-a-loop":"Calls Inside A Loop",
            "assembly-usage":"Assembly Usage",
            "unindexed-erc20-event-parameters":"Unindexed Erc20 Event Parameters",
            "conformance-to-solidity-naming-conventions":"Conformance To Solidity Naming Conventions",
            "too-many-digits":"Too Many Digits",
            "state-variables-that-could-be-declared-constant":"State Variables That Could Be Declared Constant",
            "public-function-that-could-be-declared-as-external":"Public Function That Could Be Declared As External"}

#slither命名与swc id的映射
slither_id={"incorrect-versions-of-solidity":"102",
            "old-versions-of-solidity":"102",
            "different-pragma-directives-are-used":"103",
            "unchecked-low-level-calls":"104",
            "low-level-calls":"104",
            "functions-that-send-ether-to-arbitrary-destinations":"105",
            "suicidal":"106",
            "reentrancy-vulnerabilities":"107",
            "uninitialized-storage-variables":"109",
            "deprecated-standards":"111",
            "controlled-delegatecall":"112",
            "dangerous-usage-of-tx.origin":"115",
            "block-timestamp":"116",
            "void-constructor":"118",
            "state-variable-shadowing-from-abstract-contracts":"119",
            "local-variable-shadowing":"119",
            "state-variable-shadowing":"119",
            "right-to-left-override-character":"130",
            "unused-state-variables":"131",
            "dangerous-strict-equalities":"132",
            "uninitialized-state-variables":"003",
            "incorrect-erc20-interface":"004",
            "incorrect-erc721-interface":"005",
            "contracts-that-lock-ether":"006",
            "constant-functions-using-assembly-code":"007",
            "constant-functions-changing-the-state":"008",
            "unchecked-send":"009",
            "uninitialized-local-variables":"010",
            "unused-return":"011",
            "builtin-symbol-shadowing":"012",
            "calls-inside-a-loop":"013",
            "assembly-usage":"014",
            "unindexed-erc20-event-parameters":"015",
            "conformance-to-solidity-naming-conventions":"016",
            "too-many-digits":"017",
            "state-variables-that-could-be-declared-constant":"018",
            "public-function-that-could-be-declared-as-external":"019"}